version: 2

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - binary: tfx
    ldflags: 
      - -s -w -X github.com/straubt1/tfx/version.Version={{ .Version }}
      - -s -w -X github.com/straubt1/tfx/version.Build={{ .ShortCommit }}
      - -s -w -X github.com/straubt1/tfx/version.Date={{ .Date }}
      - -s -w -X github.com/straubt1/tfx/version.BuiltBy=goreleaser

    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      
archives:
  - id: tfx
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    wrap_in_directory: true

homebrew_casks:
  - name: tfx
    ids:
      - tfx
    binaries:
      - tfx
    directory: Casks
    skip_upload: "{{ .IsSnapshot }}"
    repository:
      owner: straubt1
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
      branch: main
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "brew: update tfx cask to {{ .Tag }}"
    homepage: "https://tfx.rocks/"
    description: "TFx is a standalone CLI tool for HCP Terraform and Terraform Enterprise."

nfpms:
  - id: tfx
    vendor: straubt1
    homepage: https://tfx.rocks/
    maintainer: "Tom Straub <straub@hashicorp.com>"
    description: "TFx is a standalone CLI for HCP Terraform and Terraform Enterprise"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

dockers_v2:
  - dockerfile: Dockerfile
    images:
      - 'ghcr.io/straubt1/{{.ProjectName}}'
    tags:
      - '{{ .Tag }}'
      - 'latest'
    platforms:
      - linux/amd64
      - linux/arm64
    flags:
      - "--pull"
    labels:
      "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/straubt1/tfx/main/README.md"
      "io.artifacthub.package.maintainers": "[{\"name\":\"Tom Straub\",\"email\":\"tstraub@hashicorp.com\"}]"
      "io.artifacthub.package.license": "MIT"
      "org.opencontainers.image.description": "TFx is a standalone CLI for HCP Terraform and Terraform Enterprise"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999