version: '3'

dotenv: ['.env', 'secrets/.env']

tasks:
  go-build:
    desc: Build Go binary
    cmds:
      - go build .
  go-build-all:
    desc: Build all Go binaries
    cmds:
      - |
          BUILD_SHA="local" BUILD_DATE=$(date) BUILT_BY="me" \
          goreleaser release --snapshot --clean
  go-upgrade:
    desc: Upgrade Go dependencies
    cmds:
      - go get -u ./...
      - go mod tidy
  test:
    desc: Run unit tests
    cmds:
      - go test -v ./...
  test-integration:
    desc: Run integration tests (requires TFE_HOSTNAME, TFE_TOKEN, TFE_ORGANIZATION env vars)
    cmds:
      - go test -tags=integration -v ./...
  test-all:
    desc: Run all tests (unit + integration)
    cmds:
      - task: test
      - task: test-integration
  serve-docs:
    desc: Serve documentation site
    cmds:
      - mkdocs serve -f site/mkdocs.yml