name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Lint
      #   uses: golangci/golangci-lint-action@v2
      #   with:
      #     version: v1.32.2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
      - name: Install gox
        run: go get github.com/mitchellh/gox
      - name: Install zip
        run: |
          sudo apt-get update -q
          sudo apt-get install zip -q

      - name: Cross compile
        run: |
          gox \
            -os="linux darwin windows" \
            -ldflags="-X 'github.com/straubt1/tfx/version.Build=${{ github.sha }}' -X 'github.com/straubt1/tfx/version.Date=$(date)' -X 'github.com/straubt1/tfx/version.BuiltBy=github'" \
            -arch="amd64 arm64" \
            -output "./pkg/{{.OS}}_{{.Arch}}/tfx" \
            .
      - name: Print version
        run: ./pkg/linux_amd64/tfx --version
        
      # Package all binaries together
      - uses: actions/upload-artifact@v2
        with:
          name: tfx-artifacts
          path: ./pkg/*     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}